GET https://phonebook-botcamp.onrender.com/api/persons
###
GET https://phonebook-botcamp.onrender.com/api/persons/3
###
POST https://phonebook-botcamp.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Attis Alejandro",
    "number": "0987800027"
}
###
DELETE https://phonebook-botcamp.onrender.com/api/persons/3